[global]
listen = "192.168.0.126:8080"
video_path = "/home/melifaro/go/cv/video"
minimum_area = 3000.0 # pixels
fade_delay = 3000 # 3 seconds
init_delay = 10000 # 10 seconds
max_length = 90000 # 30 second video
pprof = "off"

[[webcam]]
id = 0
name = "webcam 0"
http_name = "cam0"
debug = "off"
record = "on"
# resolution = "1024x768@10"
# resolution = "1920x1080@15"
resolution = "2048x1536@15"
camera_codec = "MJPG"
focus_area = "7,50-50,95"
